### ISSUE TITLE
Support/utilize the new `LogOutputChannel` feature

### ISSUE THREAD

**Issue by bwateratmsft** [microsoft/vscode-azuretools#1358]
All of our extensions use output channels, and the core utils package pretty much depends on it. But, VSCode recently added a `LogOutputChannel` concept, along with per-extension verbosity levels, that I think are a nice upgrade. We can use this to replace our existing output channels in VSCode 1.73+. That said, I think we should try to maintain backwards compatibility if at all possible.

**Comment by alexweininger** [comment]
Our extensions are currently utilizing the output channel as an activity log or notification channel rather than a proper log channel. Because of this, we hardly log anything.

I really want us to start doing proper logging in extensions, which will let users provide us with more detailed bug reports, etc.

Ideally, we phase out using the output channel for "feature"-type logs and use the activity log instead. Until we phase those out, I think we'll need to do one of two things:

1. Convert the existing output channel implementation to a log output channel. All things that we're currently logging to it will be "info" level logs and shown by default. We can add lower level logs ("debug", "trace") and unless users change the log level they won't see it.
2. Extensions continue using an output channel for "feature"-type logs. But they also register a log output channel and start output more details logs there. We'll remove the output channel once "feature"-type logs are all migrated to the activity log.

I think Option 1 is probably best because we don't want to create 2 channels for each extension.

**Comment by bwateratmsft** [comment]
Agreed. Two channels is too much. I think we should change the current implementation and extensions can slowly move toward more logging.
