### ISSUE TITLE
[Discussion] Duplicate subscription lists from multiple extensions

### ISSUE THREAD

**Issue by blackchoey** [microsoft/vscode-azuretools#350]
I installed several Azure related extensions through the [Azure Tools](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-node-azure-pack) extension pack. When I opens the Azure view, each extension shows a subscription list for me, which is annoying. Seems all the extensions are using "vscode-azureextensionui" package for the subscription tree view. Is there any possibility to consolidate the lists into one (like the [VS Cloud Explorer](https://marketplace.visualstudio.com/items?itemName=ms-azuretools.CloudExplorerForVS) does)?
![image](https://user-images.githubusercontent.com/16605901/49422929-9fbcaa00-f7d0-11e8-8572-1bb266231120.png)

**Comment by EricJizbaMSFT** [comment]
I've had some offline discussions with @fiveisprime and @nturinski related to this - going to summarize here. There's two main reasons we haven't done anything related to this yet:
1. The majority of people only have one extension installed:
|Extension Count|Percent|
|---|---|
|1|%|
|1|%|
|1|%|
|1|%|

On the plus side, either most people don't have that many subscriptions or they've successfully figured out how to filter subscriptions. Here is the percent of machines by count of subscriptions:
![Screen Shot 2020-02-06 at 5 21 00 PM](https://user-images.githubusercontent.com/11282622/73993176-471dfb00-4906-11ea-8a1b-8ffff0989acb.png)

A few ideas to improve this - some of this discussed with @nturinski and @fiveisprime offline:
### Option A

If the user only has one subscription, hide the subscription node and just display the resources. This looks cleaner for sure, but now there's no entry point in the tree view for things like "Select Subscriptions", "Create Function App..." or "Create Function App... (Advanced)". We could add buttons in the title bar of the viewlet, but I think it would look gross with too many buttons.

### Option B

Read the default subscription from the az cli and automatically apply that as a filter if no VS Code filter is defined in settings. Theoretically this would increase the percent of "1" in the graph above, but not sure if users would be confused when suddenly fewer subscriptions are displayed.

### Option C

Never display subscriptions and force users to pick a "default", similar to the az cli. This will definitely simplify some things, but it seems too restrictive when over half of users already only have 1 subscription. IMO we would also have to make it obvious how to change the default and I'm not sure how we'd do that

### Option D

Expand a subscription by default. Saves one click for the user and might look better in the sense that the resources are now the main focus instead of a duplicated list of collapsed subscriptions. One question is: what do we do if they have multiple subscriptions - expand the first? Expand none? Could leverage a "default" here as well

**Comment by fiveisprime** [comment]
I'd love to see both A and B. You're right that we'll need to discuss how to source the entry points for actions that typically occur on the root subscription node, but I'd really like to see the UI cleaned up.

**Comment by EricJizbaMSFT** [comment]
Talked during standup. Need to investigate if we can have a dropdown for subscriptions like the remote extensions do:
![Screen Shot 2020-02-07 at 3 11 49 PM](https://user-images.githubusercontent.com/11282622/74072740-b2c29f80-49bc-11ea-80f4-6ccf5d317737.png)

Also for "Create" vs "Create (advanced)" maybe the plus button should prompt users to pick either basic or advanced
![Screen Shot 2020-02-07 at 3 14 51 PM](https://user-images.githubusercontent.com/11282622/74072769-c66e0600-49bc-11ea-911d-da522e735094.png)

**Comment by EricJizbaMSFT** [comment]
Seems like that dropdown is [coming from VS Code core](https://github.com/microsoft/vscode/blob/master/src/vs/workbench/contrib/remote/browser/remote.ts#L501), not a remote extension itself. Filed https://github.com/microsoft/vscode/issues/90268
