### ISSUE TITLE
Problems connecting to Azure App 

### ISSUE THREAD

**Issue by Alistair67** [Microsoft/vscode-azuretools#41]
Using ms-azuretools.vscode-azureappservice

When I try to sign in to the Azure account for the app I want to manage I am taken to a page that asks me to enter a code the application sent to my device. I am using my boss's Microsoft Account as that is the account used to create the app on Azure. The code has not come to his phone or work PC and so I assume is being sent to his personal PC which we don't have access to in the office. Is there any way to get the extension to connect me using the login and password, or is there some way to get the code to go to a particular device on his account like his work PC or phone?

Sorry if this is not the right place to post this, but I can't find anything about this online and it is getting extremely frustrating. Any help appreciated.

Cheers, Alistair

**Comment by nturinski** [comment]
Hi @Alistair67,

I'm sorry to hear that you're dealing with such a frustrating sign-in experience.  If I understand you correctly, you have been able to copy the code and paste it into the login screen that the extension directs you to, but you haven't been able to get access to the account due to two-step authentication?

If your boss can log into his account, he should be able to change the primary number or add a secondary number.  Then when you try to login through the extension, that new number should have the approval code.  I've posted a link below that will hopefully guide you through this process.

https://docs.microsoft.com/en-us/azure/multi-factor-authentication/end-user/multi-factor-authentication-end-user-manage-settings

**Comment by EricJizbaMSFT** [comment]
Closing this as there hasn't been any update in a while. If you're still having issues, I recommend posting an issue on the Azure Account repo, which specifically deals with the sign-in experience for VS Code: https://github.com/Microsoft/vscode-azure-account
