### ISSUE TITLE
Add utils to detect .NET project

### ISSUE THREAD

**Issue by timheuer** [Microsoft/vscode-azuretools#455]
Similar to the utils to detect if the project is a java project, there should be a similar utils to detect if the project is a .NET/C# project.  This will help other extensions flow their logic based on this information better.

**Comment by EricJizbaMSFT** [comment]
@timheuer are you talking about these java utils? https://github.com/Microsoft/vscode-azuretools/blob/master/appservice/src/utils/javaUtils.ts#L55 As @nturinski mentioned [here](https://github.com/Microsoft/vscode-azuretools/pull/434#pullrequestreview-211387268), we actually don't want those utils to live in this package. How are you planning on using it? Are you working on another extension?

**Comment by timheuer** [comment]
yeah something similar.  There are other Azure extensions that would need to know some more context in order to kick off different settings.  Having an 'am i a .NET project' capability in a core location will help other Azure extensions and not reproduce that multiple places.

Unfortunately the workspaceContains/onLanguage triggers aren't enough because those are launch/activation triggers and not something that can be queries later.

**Comment by EricJizbaMSFT** [comment]
Can you give examples of extensions? The current java utils are in an app service package, and so only app service extensions should be using it. I don't think java utils or c# utils are specific to app service, which is why we only reluctantly added them in the first place (and why we plan to remove them).

I agree a common capability could be useful, but I want to avoid these packages becoming a dumping grounds for random utils.

**Comment by timheuer** [comment]
If the plan is to remove the javaUtils, that makes sense.  This would be for other app service usage as well.  We just had a discussion and think we'll own our own dotnetUtils extension...closing.
