### ISSUE TITLE
[Question] Guidelines for using AzExtOutputChannel

### ISSUE THREAD

**Issue by formulahendry** [microsoft/vscode-azuretools#632]
We are evaluating the vscode-azureextensionui to be used in [Azure IoT Hub Toolkit](https://marketplace.visualstudio.com/items?itemName=vsciot-vscode.azure-iot-toolkit).
We see that  we need to create a `AzExtOutputChannel` before using the UI package.
As we already have three OutputChannel created in Azure IoT Hub Toolkit. Therefore, we want to know:

-  Difference between createAzExtOutputChannel and createOutputChannel
- Is there any guideline or docs about using AzExtOutputChannel?
- Where is AzExtOutputChannel used in the UI package?

In the end, we want to know: if we introduce a new tree view. Shall we use a new AzExtOutputChannel, or leverage an existing vscode.OutputChannel?

Thanks a lot!

**Comment by nturinski** [comment]
Hi @formulahendry,

- The main difference between `createAzExtOutputChannel` and `createOutputChannel` is that `createAzExtOutputChannel` requires an extension prefix parameter.  This parameter is used to look up the user's vscode settings.  Specifically, `AzExtOutputChannel` respects a setting named `extensionPrefix.enableOutputTimestamps` which allows users to disable prepending messages with timestamps.
- Documentation about `AzExtOutputChannel` can be found here: https://github.com/microsoft/vscode-azuretools/blob/master/ui/index.d.ts#L1112-L1129-
- In the UI package, AzExtOutputChannel is used anywhere we call `ext.outputChannel.append...`.  This is typically used to report output from most actions from our extension.  In your own extension, you would need code to register your extension's variables.  That code looks like this:
```
ext.context = context;
ext.reporter = createTelemetryReporter(context);

const ui: IAzureUserInput = new AzureUserInput(context.globalState);
ext.ui = ui;

ext.outputChannel = createAzExtOutputChannel("Azure App Service", ext.prefix);
context.subscriptions.push(ext.outputChannel);

registerUIExtensionVariables(ext);
```

We register these UI elements so that we can access the UI (including the `outputChannel`) from any function rather than by having to pass the channel as a parameter.

The main reason we use `AzExtOutputChannel` rather than just `OutputChannel` is so that we can easily maintain consistent output behavior between our extensions.   Right now, the main benefit is to be able to have timestamps and resource names pre-pended to all output. That looks like this:

![image](https://user-images.githubusercontent.com/5290572/70007084-f4018380-1523-11ea-8022-4dd73ceac07a.png)

But all existing `OutputChannel` behavior that has been implemented in your extension should behave the same if all you do is change `createOutputChannel` to `createAzExtOutputChannel` since it's just a wrapper.  So any call to `outputChannel.appendLine()` or `outputChannel.append()` will not have timestamps.

I hope this helps in answering your questions.  Please let me know if there was anything else that I could clarify 😃

**Comment by formulahendry** [comment]
Thanks @nturinski a lot for your detailed explanation. It helps a lot!
I could close this issue now, 😄
