### ISSUE TITLE
`ITelemetryReporter.sendErrorTelemeryEvent` is mis-named

### ISSUE THREAD

**Issue by karolz-ms** [microsoft/vscode-azuretools#693]
I understand that `ITelemetryReporter.sendErrorTelemeryEvent` is meant to send all sorts of telemetry events, not just events about errors. If my understanding is correct, then the name is bad. It is very confusing to read code that uses `ITelemetryReporter` and calls `sendError()` for telemetry that *is not* an error report.

Please rename the method back to `sendTelemetryEvent`.

**Comment by EricJizbaMSFT** [comment]
A few points:
1. We can't change it "back" because it's a different method with different behavior. If errorProps is undefined, _all properties will get dropped_. At least with a new name, people will have to think twice about what they're doing and hopefully realize they need to change something
1. `sendTelemetryEvent` still exists if you use `TelemetryReporter` directly from `vscode-extension-telemetry` and we're not preventing the use of that in any way
1. We're simply matching the name from [the vscode telemetry package](https://github.com/microsoft/vscode-extension-telemetry#sending-errors-as-events). I don't think our package should be re-defining core VS Code names, but I agree it's not a great name and I would "plus one" if you file an issue on their repo (but related to the above points, it would have to be a new name, not the "old" name for a separate method that still exists)

**Comment by EricJizbaMSFT** [comment]
I just want to emphasize that the current solution is a compromise that neither Stephen or I fully like. To re-iterate my position from [this thread](https://github.com/microsoft/vscode-azuretools/pull/686#discussion_r416981016), my top preference is to have `ITelemetryReporter` directly match `TelemetryReporter` from the `vscode-extension-telemetry` package (aka we allow both `sendTelemetryEvent` and `sendErrorTelemeryEvent`) so that we don't "own" any of this naming/design and we can punt all issues to them

**Comment by StephenWeatherford** [comment]
My preference would be to just expose sendTelemetryEvent and have it handle common sensitive properties under the cover, with the ability to add additional error properties optionally. I.e. out interface is distinct from the internal one.  I'd like to see callstack/error/errorMessage/errorid always handled.

**Comment by StephenWeatherford** [comment]
For reference, here are the changes in the ARM extension: https://github.com/microsoft/vscode-azurearmtools/pull/664/files

**Comment by bwateratmsft** [comment]
>If errorProps is undefined, all properties will get dropped.

@EricJizbaMSFT Do we need to be defining that everywhere then? Or only where we call `ITelemetryReporter.sendTelemetryErrorEvent` instead of using `callWithTelemetry...`?

**Comment by karolz-ms** [comment]
@EricJizbaMSFT I do not think at maintaining fidelity with VSCode `TelemetryReporter` should be a goal for `vscode-azuretools` at all

Instead, given the obvious problems with the VSCode `TelemetryReporter`, the primary goal for `vscode-azuretools` should be to provide **a contract for sending telemetry** that is easy to use, has sensible defaults, and results in easy-to-read, understandable code. So:
- All telemetry properties should be included by default. There might be a set of pre-defined properties that are considered 'sensitive' and excluded by default.
- VSCode policies regarding telemetry sending and usage should be followed, without the user having to write any extra code to achieve that.
- The name of the method(s) should reflect their purpose

What @StephenWeatherford did in the above mentioned PR, or how `callWithTelemetryAndErrorHandling` does are good examples of what I am talking about. Having to pass an empty array as a value for an optional parameter, in order to make the API to what is necessary in 80% of the cases, is a counter-example.

I am just asking for `vscode-azuretools` `ITelemetryReporter` interface to conform to these design guidelines.

**Comment by EricJizbaMSFT** [comment]
Why should we own that though? The team that owns `vscode-extension-telemetry` has been responsive to Stephen and Brandon's suggestions in the past few days - so I would prefer you give your feedback to them and we try to get it fixed for everyone

**Comment by StephenWeatherford** [comment]
They can't own which properties should be considered sensitive by default.  We can, since our own our own usage patterns.

**Comment by EricJizbaMSFT** [comment]
Another reason I (personally) don't want to own this is because none of the extensions I work on use `sendTelemetryEvent`. I did a search and the following extensions had zero results: Functions, App Service, Cosmos DB, Storage, Virtual Machines, Resource Groups, and Event Grid. They only use `registerCommand`, `registerEvent` or `callWithTelemetryAndErrorHandling`

Docker (@karolz-ms 👀) and ARM (@StephenWeatherford 👀) may be the only two actually using these methods. I tried to figured out why you guys were using it and chose Docker as my test subject. However, I think all uses could be removed. The [save event](https://github.com/microsoft/vscode-docker/blob/ac31190389c1069da12d6671ee92ad18eb98c793/src/registerListeners.ts#L23) could use `registerEvent`, and the [survey](https://github.com/microsoft/vscode-docker/blob/7302d48b6e0db5f9d8549e15f3e3dad540b8cd92/src/telemetry/surveys/activeUseSurvey.ts#L58) [cases](https://github.com/microsoft/vscode-docker/blob/f4e3f334914eca3f6e6ffd4d06271ff84a5cbedb/src/utils/nps.ts#L72) could use `callWithTelemetryAndErrorHandling`. For example in the survey example, you would have no idea if a stupid null ref exception was preventing all surveys. If you wrap all of the survey code with `callWithTelemetryAndErrorHandling`, you would get that error tracked by default.

Now I'm leaning towards completely getting rid of `ITelemetryReporter` from the UI package because it has such low usage.

**Comment by karolz-ms** [comment]
I think we could live with that. @bwateratmsft ?

**Comment by StephenWeatherford** [comment]
I'm good with that.  https://github.com/microsoft/vscode-azurearmtools/pull/664/files

**Comment by bwateratmsft** [comment]
I'd have to look into `registerEvent`. For `TelemetryReporterProxy`, should we directly call into `vscode-extension-telemetry`? We still need to keep that class for the experimentation service.

**Comment by bwateratmsft** [comment]
As I think about it, the _only_ way to be able to use the experimentation service, while internalizing `ITelemetryReporter`, is for the experimentation service adapter to move up here into `vscode-azureextensionui`. The experimentation service needs a telemetry reporting object that can set shared properties assigned to _all_ events; not possible if the telemetry reporter is inaccessible.

**Comment by EricJizbaMSFT** [comment]
I don't know enough about your experimentation service to really comment on it, but seems fishy that the second we try to remove `ITelemetryReporter` there's something new that just HAS to have it 🐟👀😝

At the moment, the only thing `createTelemetryReporter` really provides is the `DebugReporter`. Otherwise it just passes along the exact same `TelemetryReporter` from `vscode-extension-telemetry`. Is your main concern around `DebugReporter`?

**Comment by bwateratmsft** [comment]
My main concern is about shared properties. To use the experimentation service (which lets us do nice things like flighting and statistical analysis), you have to provide it an implementation of `IExperimentationTelemetry`, which has two methods (`postEvent`, `setSharedProperty`). The former is not difficult and could easily directly call `vscode-extension-telemetry`. However, the latter would be the breaking bit.

In order to actually use the experimentation service, you have to allow it to attach a couple properties (not sure exactly what) to _all_ the telemetry events--including everything currently managed up in `vscode-azureextensionui`. The plan was to let [`TelemetryReporterProxy`](https://github.com/microsoft/vscode-docker/pull/1934/files#diff-cf2a1c1e8113d52bda4fec40b44d9c86) implement that interface--since already all of the telemetry calls route through it, it's easy to do there.

Either we'd need a `setSharedProperty` method up here in `vscode-azureextensionui`, or, `ITelemetryReporter` has to stay public 😕

**Comment by EricJizbaMSFT** [comment]
Just another idea, what if we had some sort of way to register an error handler or telemetry handler that was called right before `handleError` and `handleTelemetry` in [this file](https://github.com/microsoft/vscode-azuretools/blob/master/ui/src/callWithTelemetryAndErrorHandling.ts). Something like this:
```
registerErrorHandler(handler: (callbackId: string, context: IActionContext, error: unknown) => Promise<void>): Disposable
registerTelemetryHandler(handler: (callbackId: string, context: IActionContext) => Promise<void>): Disposable
```

A few ideas on how that could be used:
1. Add shared properties? Hopefully?
1. Essentially default `Report an Issue` to false for your extension if you find it too annoying
1. Catch all "Entry not found in cache" errors (stupid [errors](https://github.com/microsoft/vscode-azurefunctions/issues/2068)) and tell them to just reload VS Code or sign in /sign out to fix

**Comment by bwateratmsft** [comment]
That would work. Long as we're on the subject do you have ideas on how we could do `postEvent` without using `vscode-extension-telemetry` directly? I guess it'd be awkward but I think this could work right?
```typescript
public postEvent(eventName: string, props: Map<string, string>): void {
    // Convert their Map<string, string> to { [key: string]: string }
    callWithTelemetryAndErrorHandling(... {
        context.telemetry.properties = properties;
    });
}
```

**Comment by EricJizbaMSFT** [comment]
Yeah I feel like that's a good short term solution, and perhaps the best long-term solution is to move the experimentation service to `vscode-azureextensionui` (maybe after Docker tries it out for a bit?) so that it can use the internal reporter directly

**Comment by bwateratmsft** [comment]
I guess the only thing I'd add to that `registerErrorHandler` / `registerTelemetryHandler` is a pattern I've seen elsewhere, wherein the `ErrorHandler` / `TelemetryHandler` can return a value indicating whether the error/telemetry has been fully handled (and therefore, the rest of the method need not run), or not.

**Comment by StephenWeatherford** [comment]
> context.telemetry.properties = properties;

This is exactly what I'm doing to forward telemetry from the language server.

**Comment by EricJizbaMSFT** [comment]
@bwateratmsft Do we think properties like `context.errorHandling.suppressDisplay` and `context.telemetry.suppressAll` are good enough in that respect? I know what pattern you're talking about (i.e. `DebugConfigurationProvider.resolveDebugConfiguration`), but it feels a little odd to completely skip other handlers since I think we have to run them in an arbitrary order

**Comment by bwateratmsft** [comment]
That makes sense to me.
