### ISSUE TITLE
Create custom error handling

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azuretools#78]
Today there is no way to make a custom error as vscode-azureextensionui has automatic error handling.  We should make an error to allow for custom error handling while still tracking it in the telemetry,

**Comment by StephenWeatherford** [comment]
Note: one way to do this is to use AzureEventHandler.runWithTelemetry(). It will need a separate telemetry key, but will register with telemetry whether it succeeded or failed. You could then safely swallow the exception returned.  I'm working on a PR to move this out of AzureEventHandler to make it easier to use.

**Comment by EricJizbaMSFT** [comment]
The error would basically be 'DontShowToUserError', with the assumption that the original code displays it to the user. I'm not sure what you mean by 'handle a single error', since whoever throws the error also handles displaying it to the user. That means you could handle any type of error. For example, maybe the error is "Failed to find <insert tool> installed" and the custom handling could be to direct the user to documentation, or even to install that tool for the user.

I'm hesitant to use `AzureActionHandler. callWithTelemetry` for code that is already being tracked. My main concern is that we'll end up with multiple telemetry keys that each have partial information about the same command - I would prefer to have all that information associated with one telemetry key.

**Comment by EricJizbaMSFT** [comment]
@StephenWeatherford In regards to this -> "I'm working on a PR to move this out of AzureEventHandler to make it easier to use.", could you create a Github issue to describe the scenario you're fixing and just to track the work?

**Comment by StephenWeatherford** [comment]
'DontShowToUserError' is likely the right approach if the activity actually fails because of it (one error).  There are scenarios where you have fallback behavior that may make the activity succeed (or you at least do something), but you still want to know about the errors/decisions that occurred along the way. Discuss Monday.

**Comment by StephenWeatherford** [comment]
Another use case: vscode-azurestorage#87.
