### ISSUE TITLE
No indication that extension is Loading in the UI

### ISSUE THREAD

**Issue by nturinski** [Microsoft/vscode-azuretools#84]
The extensions used to have a node that said "Loading..." when the extension first activated.  Because the azureaccounts extension caches now, we probably lost this UI functionality.

**Comment by StephenWeatherford** [comment]
I agree this can be confusing.

**Comment by EricJizbaMSFT** [comment]
I agree we should fix this if possible, but I will point out that in the past there was also a delay before the "loading..." node showed up (we just didn't notice it because it was dwarfed by how long it was in the "loading..." state)
![refresh](https://user-images.githubusercontent.com/11282622/36700567-fb3448a6-1b04-11e8-8f8e-6ba2a39b5fc5.gif)
![refresh2](https://user-images.githubusercontent.com/11282622/36700568-fc4fbb4e-1b04-11e8-9d6b-147369bad6f3.gif)

Because of that, I don't think the bug is related to caching the subscription information. Just a guess, but it's possible the delay is introduced by `extensions.getExtension<AzureAccount>('ms-vscode.azure-account');`

**Comment by StephenWeatherford** [comment]
This was always an annoyance, even before the caching. Oh, the many times I’ve wondered, “is it loading, or is something wrong?”.  And if you try clicking any buttons during that time, some extensions give errors.

Ideally, as soon as we get activated, we should put up some UI.

**Comment by EricJizbaMSFT** [comment]
@StephenWeatherford @fiveisprime can we close this now?

A while back VS Code added a few loading indicators (the blue bar below Azure and the blue thing on the Azure icon):
![screen shot 2019-02-20 at 11 59 10 am 2](https://user-images.githubusercontent.com/11282622/53120591-07001580-3507-11e9-93de-f90e9cedadc0.png)

Plus we did all that webpack work to speed this up anyways (and it's not like we can display anything while we're activating)

**Comment by StephenWeatherford** [comment]
I think so, thanks.
